### ISSUE TITLE
Don't hardcode tray icon on Linux 

### ISSUE THREAD

**Issue by bilelmoussaoui** [alkasir/alkasir#86]
The Tray icon name is hardcoded on Linux 
https://github.com/alkasir/alkasir/blob/c8ed030689f63da6682c9a90ce7bb6a2cea2ae8c/vendor/github.com/thomasf/systray/systray_linux.c#L34 will generate a unique icon name. 
While you can use https://developer.ubuntu.com/api/devel/ubuntu-12.04/c/appindicator/libappindicator-app-indicator.html#app-indicator-set-icon-full 
`app_indicator_set_icon_full("alkasir-indicator"....`
Could this be fixed ? 
This way the icon can be themed by theme designers!

**Comment by thomasf** [comment]
Moved issue to https://github.com/thomasf/systray/issues/2
